### ISSUE TITLE
Leaflet 1.0.2 compatibility

### ISSUE THREAD

**Issue by cocoto** [iosphere/Leaflet.hotline#11] opened 2016-11-22 10:02 UTC
The module is not compatible with the new Leaflet 1.0.2 library.
Replacing import lines in [demo](//github.com/iosphere/Leaflet.hotline/blob/master/demo/index.html) by
````
<script src="//cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.2/leaflet.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.2/leaflet.css" />
````

Leads to no display (and no javascript warning / error).
The 1.0.1 version works well, I'm going to analyse [1.0.1 -> 1.0.2 patchnote](//github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#102-november-21-2016)

**Comment by cocoto** [comment] 2016-11-22 10:34
I found the commit associated https://github.com/Leaflet/Leaflet/commit/4c484462dc4d646cb43adc0585401d28d878330d to the bug

**Comment by klaftertief** [comment] 2016-11-22 10:43
Thanks for analysing the problem.
I'm happy to accept a pull request. Will have a look at it in the next couple of days otherwise.

**Comment by d4l4n** [comment] 2016-12-09 09:24
The patch works for me. 
 In addition, mouseover events work too.

**Comment by miquelmassot** [comment] 2016-12-09 17:29
I'm trying to use it in 1.0.2 and it's not working. When loading the canvas the property `layer._pxBounds`
is not defined, and therefore the hotline is not painted.

**Comment by klaftertief** [comment] 2016-12-12 09:58
Sorry for being unresponsive. A new release is just a couple of days ahead...

**Comment by klaftertief** [comment] 2017-02-28 22:28
Should be fixed with the new version https://github.com/iosphere/Leaflet.hotline/releases/tag/v0.4.0

@miquelmassot Does this fix your issue as well. I could not reproduce it.

**Closed by klaftertief** 2017-02-28 22:28 UTC
